/**
 * Business error codes
 */

export const ERROR_CODES = {
  // Authentication errors
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  MFA_REQUIRED: 'MFA_REQUIRED',
  MFA_INVALID: 'MFA_INVALID',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // Validation errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',

  // Resource errors
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  CONFLICT: 'CONFLICT',

  // Eligibility errors
  ELIGIBILITY_CONTRACT_INACTIVE: 'ELIGIBILITY_CONTRACT_INACTIVE',
  ELIGIBILITY_CONTRACT_EXPIRED: 'ELIGIBILITY_CONTRACT_EXPIRED',
  ELIGIBILITY_WAITING_PERIOD: 'ELIGIBILITY_WAITING_PERIOD',
  ELIGIBILITY_LIMIT_REACHED: 'ELIGIBILITY_LIMIT_REACHED',
  ELIGIBILITY_EXCLUDED_SERVICE: 'ELIGIBILITY_EXCLUDED_SERVICE',
  ELIGIBILITY_PROVIDER_NOT_CONTRACTED: 'ELIGIBILITY_PROVIDER_NOT_CONTRACTED',
  ELIGIBILITY_SERVICE_NOT_COVERED: 'ELIGIBILITY_SERVICE_NOT_COVERED',

  // Tarification errors
  TARIFF_NOT_FOUND: 'TARIFF_NOT_FOUND',
  TARIFF_BAREME_NOT_FOUND: 'TARIFF_BAREME_NOT_FOUND',
  TARIFF_INVALID_ITEM: 'TARIFF_INVALID_ITEM',

  // Fraud errors
  FRAUD_BLOCKED: 'FRAUD_BLOCKED',
  FRAUD_REVIEW_REQUIRED: 'FRAUD_REVIEW_REQUIRED',

  // Claim errors
  CLAIM_ALREADY_PROCESSED: 'CLAIM_ALREADY_PROCESSED',
  CLAIM_INVALID_STATUS: 'CLAIM_INVALID_STATUS',

  // Reconciliation errors
  RECONCILIATION_NO_CLAIMS: 'RECONCILIATION_NO_CLAIMS',
  RECONCILIATION_ALREADY_PAID: 'RECONCILIATION_ALREADY_PAID',

  // System errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const ERROR_MESSAGES: Record<ErrorCode, string> = {
  [ERROR_CODES.INVALID_CREDENTIALS]: 'Email ou mot de passe incorrect',
  [ERROR_CODES.TOKEN_EXPIRED]: 'Session expirée, veuillez vous reconnecter',
  [ERROR_CODES.TOKEN_INVALID]: 'Token invalide',
  [ERROR_CODES.MFA_REQUIRED]: 'Authentification à deux facteurs requise',
  [ERROR_CODES.MFA_INVALID]: 'Code MFA invalide',
  [ERROR_CODES.UNAUTHORIZED]: 'Authentification requise',
  [ERROR_CODES.FORBIDDEN]: 'Accès non autorisé',

  [ERROR_CODES.VALIDATION_ERROR]: 'Erreur de validation',
  [ERROR_CODES.INVALID_INPUT]: 'Données invalides',

  [ERROR_CODES.NOT_FOUND]: 'Ressource non trouvée',
  [ERROR_CODES.ALREADY_EXISTS]: 'Cette ressource existe déjà',
  [ERROR_CODES.CONFLICT]: 'Conflit avec une ressource existante',

  [ERROR_CODES.ELIGIBILITY_CONTRACT_INACTIVE]: 'Contrat inactif',
  [ERROR_CODES.ELIGIBILITY_CONTRACT_EXPIRED]: 'Contrat expiré',
  [ERROR_CODES.ELIGIBILITY_WAITING_PERIOD]: 'Période de carence en cours',
  [ERROR_CODES.ELIGIBILITY_LIMIT_REACHED]: 'Plafond annuel atteint',
  [ERROR_CODES.ELIGIBILITY_EXCLUDED_SERVICE]: 'Service exclu du contrat',
  [ERROR_CODES.ELIGIBILITY_PROVIDER_NOT_CONTRACTED]: 'Prestataire non conventionné',
  [ERROR_CODES.ELIGIBILITY_SERVICE_NOT_COVERED]: 'Type de soin non couvert',

  [ERROR_CODES.TARIFF_NOT_FOUND]: 'Tarif non trouvé',
  [ERROR_CODES.TARIFF_BAREME_NOT_FOUND]: 'Barème non trouvé',
  [ERROR_CODES.TARIFF_INVALID_ITEM]: 'Article invalide',

  [ERROR_CODES.FRAUD_BLOCKED]: 'Transaction bloquée pour suspicion de fraude',
  [ERROR_CODES.FRAUD_REVIEW_REQUIRED]: 'Transaction en attente de vérification',

  [ERROR_CODES.CLAIM_ALREADY_PROCESSED]: 'Demande déjà traitée',
  [ERROR_CODES.CLAIM_INVALID_STATUS]: 'Statut de demande invalide',

  [ERROR_CODES.RECONCILIATION_NO_CLAIMS]: 'Aucune demande à réconcilier',
  [ERROR_CODES.RECONCILIATION_ALREADY_PAID]: 'Bordereau déjà payé',

  [ERROR_CODES.INTERNAL_ERROR]: 'Erreur interne du serveur',
  [ERROR_CODES.DATABASE_ERROR]: 'Erreur de base de données',
  [ERROR_CODES.RATE_LIMIT_EXCEEDED]: 'Trop de requêtes, veuillez réessayer plus tard',
};
