/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        secondary: '#0051d5',
        primary: '#040d1b',
        'on-primary': '#ffffff',
        'inverse-on-surface': '#eff1f3',
        'surface-tint': '#565f70',
        'surface-bright': '#f7f9fb',
        'on-tertiary-container': '#009d6d',
        'inverse-surface': '#2d3133',
        tertiary: '#001008',
        'primary-container': '#1a2332',
        'on-surface': '#191c1e',
        error: '#ba1a1a',
        'surface-container': '#eceef0',
        'on-tertiary-fixed-variant': '#005236',
        background: '#f7f9fb',
        'on-tertiary': '#ffffff',
        'on-secondary-container': '#fefcff',
        'secondary-fixed-dim': '#b4c5ff',
        'on-tertiary-fixed': '#002113',
        'on-surface-variant': '#45474c',
        'on-primary-fixed-variant': '#3e4758',
        'tertiary-container': '#002919',
        outline: '#75777d',
        'on-error-container': '#93000a',
        'on-background': '#191c1e',
        'surface-container-lowest': '#ffffff',
        'on-secondary': '#ffffff',
        'inverse-primary': '#bec7db',
        'primary-fixed-dim': '#bec7db',
        'surface-dim': '#d8dadc',
        'surface-container-high': '#e6e8ea',
        'on-primary-container': '#818a9d',
        'surface-container-highest': '#e0e3e5',
        'on-secondary-fixed': '#00174b',
        'error-container': '#ffdad6',
        'outline-variant': '#c5c6cc',
        'on-secondary-fixed-variant': '#003ea8',
        'tertiary-fixed-dim': '#4edea3',
        'secondary-fixed': '#dbe1ff',
        'primary-fixed': '#dae3f7',
        'surface-variant': '#e0e3e5',
        surface: '#f7f9fb',
        'on-error': '#ffffff',
        'tertiary-fixed': '#6ffbbe',
        'on-primary-fixed': '#131c2a',
        'surface-container-low': '#f2f4f6',
        'secondary-container': '#316bf3',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '0.75rem',
        xl: '1.25rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
